import { ResponseFetchUsers } from "./Services";

export const clientList: ResponseFetchUsers[] = [
  {
    id: 0,
    name: "Adekola Damilare",
    phone: "08165654564",
    email: "adeokola@gmail.com",
    address: "No 2, Olonade Close, Montana, Ibadan, Oyo State, Nigeria",
    agenda: "Male",
    years: 54,
    country: "Ngeria",
    dob: "04/11/20012",
    status: "married",
    occupation: "Software Engineer",
    interest: "Iceland",
    education: "Bachelor Degree",
    purpose: "Trading",
    title: "",
    description: "",
  },
  {
    id: 1,
    name: "Odusote Mayokun",
    phone: "08165654564",
    email: "adeokola@gmail.com",
    address: "No 2, Olonade Close, Montana, Ibadan, Oyo State, Nigeria",
    agenda: "Male",
    years: 54,
    country: "Ngeria",
    dob: "04/11/20012",
    status: "married",
    occupation: "Software Engineer",
    interest: "Iceland",
    education: "Bachelor Degree",
    purpose: "Trading",
    title: "",
    description: "",
  },
  {
    id: 2,
    name: "Mayokun Damilare",
    phone: "08165654564",
    email: "adeokola@gmail.com",
    address: "No 2, Olonade Close, Montana, Ibadan, Oyo State, Nigeria",
    agenda: "Male",
    years: 54,
    country: "Ngeria",
    dob: "04/11/20012",
    status: "married",
    occupation: "Software Engineer",
    interest: "Iceland",
    education: "Bachelor Degree",
    purpose: "Trading",
    title: "",
    description: "",
  },
  {
    id: 3,
    name: "Adekola Damilare",
    phone: "08165654564",
    email: "adeokola@gmail.com",
    address: "No 2, Olonade Close, Montana, Ibadan, Oyo State, Nigeria",
    agenda: "Male",
    years: 54,
    country: "Ngeria",
    dob: "04/11/20012",
    status: "married",
    occupation: "Software Engineer",
    interest: "Iceland",
    education: "Bachelor Degree",
    purpose: "Trading",
    title: "",
    description: "",
  },
  {
    id: 4,
    name: "Mayokun Kemi",
    phone: "08165654564",
    email: "adeokola@gmail.com",
    address: "No 2, Olonade Close, Montana, Ibadan, Oyo State, Nigeria",
    agenda: "Male",
    years: 54,
    country: "Ngeria",
    dob: "04/11/20012",
    status: "married",
    occupation: "Software Engineer",
    interest: "Iceland",
    education: "Bachelor Degree",
    purpose: "Trading",
    title: "",
    description: "",
  },
];
